config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :admin_users
    resources :posts
    resources :employees

    root to: "users#index"
  end

  resources :posts do
    member do
      get :approve
    end
  end

  resources :audit_logs, except: %i(new edit destroy) do
    member do
      get :confirm
    end
  end

  devise_for :users, skip: %i(registrations)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "static#homepage"
end

app/views/shared/_admin_drop_down.html.erb
<%= link_to "Admin Dashboard", admin_root_path, { class: "dropdown-item" } %>
<div class="dropdown-divider"></div>

app/views/shared/_audit_log_tab.html.erb
<li class="nav-item <%= active?(audit_logs_path) %>">
  <%= link_to "<i class='fas fa-clipboard-list'></i> Audit Logs #{sr_only_span(audit_logs_path)}".html_safe, audit_logs_path, { class: "nav-link" } %>
</li>

app/views/shared/_employee_nav_items.html.erb
<li class="nav-item <%= active?(posts_path) %>">
  <%= link_to "<i class='fas fa-user-clock'></i> Entries #{sr_only_span(posts_path)}".html_safe, posts_path, { class: "nav-link" } %>
</li>
<li class="nav-item <%= active?(new_post_path) %>">
  <%= link_to "<i class='fas fa-calendar-plus'></i> Request Overtime #{sr_only_span(posts_path)}".html_safe, new_post_path, { id: "new-post-from-nav", class: "nav-link" } %>
</li>

app/views/shared/_nav.html.erb
<div class="row">
  <div class="col-md-12">
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top navbar-dark bg-dark">
            
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="navbar-toggler-icon"></span>
      </button> <a class="navbar-brand" href="#">Overtime</a>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="navbar-nav">
          <li class="nav-item <%= active?(root_path) %>">
            <%= link_to "<i class='fas fa-home'></i> Home #{sr_only_span(root_path)}".html_safe, root_path, { class: "nav-link", alt: "Home" } %>
          </li>

          <%= render "shared/employee_nav_items" if current_user.employee? %>

          <%= render "shared/audit_log_tab" if current_user.admin? %>
        </ul>
        
        <ul class="navbar-nav ml-md-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown">Account</a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <%= render "shared/admin_drop_down" if current_user.admin? %>
              <%= link_to "Logout", destroy_user_session_path, { method: :delete, class: "dropdown-item" } %>
            </div>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</div>